using System.IO;
using System.Collections.Generic;
using System.Diagnostics;
using System.Reflection;
using System.Xml;
using GadrocsWorkshop.Helios.Util;
using System.Linq;

namespace GenerateTestMonitorSetup
{
    class GenerateTestMonitorSetup
    {
        private const int MAX_ROWS = 5;
        private const int MAX_COLUMNS = 12;

        private class Config
        {
            private static readonly int MAIN_LEFT = 1080;
            private static readonly int MAIN_TOP = 0;
            public int main_left = MAIN_LEFT;
            public int main_top = MAIN_TOP;
            public int main_width = 2560;
            public int main_height = 1440;
            public int grid_left = MAIN_LEFT + 2560;
            public int grid_top = MAIN_TOP;
            public int cell_width = 200;
            public int cell_height = 200;
        };

        static void Main(string[] args)
        {
            List<string> lines = new List<string>();

            lines.Add("_  = function(p) return p; end;");
            lines.Add($"name = _('test_all_viewports')");
            lines.Add($"description = 'Generated by Helios {Assembly.GetEntryAssembly().GetName().Name} tool'");

            Config config = new Config();

            // XXX generate locals in the script and calculate all other values from it, so it can be adapted to other screens
            lines.Add("Viewports = {");
            lines.Add("  Center = {");
            lines.Add($"    x = {config.main_left},");
            lines.Add($"    y = {config.main_top},");
            lines.Add($"    width = {config.main_width},");
            lines.Add($"    height = {config.main_height},");
            lines.Add($"    aspect = {(double)config.main_width / (double)config.main_height},");
            lines.Add("    dx = 0,");
            lines.Add("    dy = 0");
            lines.Add("  }");
            lines.Add("}");


            int row = 0;
            int column = 0;

            // also update helios overlay for labels
            XmlDocument heliosProfile = null;
            string profilePath = null;
            foreach (string documentsFolder in new string[] { "HeliosDev", "HeliosTesting", "Helios" })
            {
                profilePath = Path.Combine(System.Environment.GetFolderPath(System.Environment.SpecialFolder.MyDocuments), documentsFolder, "Profiles", "test_all_viewports.hpf");
                if (File.Exists(profilePath))
                {
                    heliosProfile = new XmlDocument();
                    heliosProfile.Load(profilePath);
                    XmlNode root = heliosProfile.DocumentElement;
                    XmlNode controlNode = root.SelectSingleNode("descendant::Control[@Name=\"Label\"]");
                    XmlNode childrenNode = controlNode.ParentNode;
                    childrenNode.RemoveAll();
                    childrenNode.AppendChild(controlNode);
                    break;
                }
            }

            // write standard viewports
            EmitViewports(lines, heliosProfile, config, ref row, ref column, ToolsCommon.StandardViewports.Known);

            // write mod-created viewports
            EmitViewports(lines, heliosProfile, config, ref row, ref column, ToolsCommon.ModViewports.Known, true);

            // main view
            lines.Add("UIMainView = Viewports.Center");
            lines.Add("GU_MAIN_VIEWPORT = Viewports.Center");

            WriteFile(lines);

            if (heliosProfile != null)
            {
                heliosProfile.Save(profilePath);
            }
        }

        private static void EmitViewports(List<string> lines, XmlDocument heliosProfile, Config config, ref int row, ref int column, IList<ToolsCommon.ViewportTemplate> known, bool viewportPrefix = false)
        {
            if (row >= MAX_ROWS)
            {
                return;
            }

            XmlNode root = null;
            XmlNode childrenNode = null;
            XmlNode controlNode = null;

            if (heliosProfile != null) {
                root = heliosProfile.DocumentElement;
                controlNode = root.SelectSingleNode("descendant::Control[@Name=\"Label\"]");
                childrenNode = controlNode.ParentNode;
            }

            foreach (ToolsCommon.ViewportTemplate template in known)
            {
                foreach (ToolsCommon.Viewport viewport in template.Viewports.Where(v => v.IsValid))
                {
                    lines.Add($"-- {template.DisplayName(viewport)}");
                    string viewportName = viewport.ViewportName;
                    if (viewportPrefix)
                    {
                        viewportName = $"{template.ViewportPrefix}_{viewport.ViewportName}";
                    }
                    lines.Add($"{viewportName} =");
                    lines.Add("{");
                    lines.Add($"  x = {config.grid_left + column * config.cell_width},");
                    lines.Add($"  y = {config.grid_top + row * config.cell_height},");
                    lines.Add($"  width = {config.cell_width},");
                    lines.Add($"  height = {config.cell_height}");
                    lines.Add("}");
                    lines.Add("");

                    if (childrenNode != null)
                    {
                        if ((row == 0) && (column == 0))
                        {
                            // crash if control is missing
                            controlNode.SelectSingleNode("./Text").InnerText = viewportName;
                        }
                        else
                        {
                            XmlNode cloned = controlNode.CloneNode(true);
                            cloned.Attributes["Name"].Value = $"Label_{row}_{column}";
                            cloned.SelectSingleNode("./Text").InnerText = viewportName;
                            cloned.SelectSingleNode("./Location").InnerText = $"{column * config.cell_width}, {row * config.cell_height}";
                            childrenNode.AppendChild(cloned);
                        }
                    }

                    column++;
                    if (column >= MAX_COLUMNS)
                    {
                        column = 0;
                        row++;
                        if (row >= MAX_ROWS)
                        {
                            return;
                        }
                    }
                }
            }
        }

        private static void WriteFile(List<string> lines)
        {
            foreach (string line in lines)
            {
                Debug.WriteLine(line);
            }
            string text = string.Join("\n", lines);
            string outputPath = Path.Combine(GadrocsWorkshop.Helios.Util.KnownFolders.SavedGames, "DCS", "Config", "MonitorSetup", "test_all_viewports.lua");
            File.WriteAllText(outputPath, text);
            outputPath = Path.Combine(GadrocsWorkshop.Helios.Util.KnownFolders.SavedGames, "DCS.OpenBeta", "Config", "MonitorSetup", "test_all_viewports.lua");
            File.WriteAllText(outputPath, text);
        }
    }
}
